name: UI & Unit Test

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build Cardx
      run: swift build -v
    - name: Run Cardx tests
      run: swift test -v

